from decimal import Decimal

from backend.economia.protocolo_crossvenue_carry_04h1 import (
    ACTIVOS_04H1, ANIOS_04H1, API_KEY_DATOS_0XARCHIVE_PERMITIDA_04H1,
    BARRAS_8H_ESPERADAS_04H1, CALCULAR_PNL_SI_GATE_COMPLETO_PASA_04H1,
    CALCULAR_PNL_SIN_GATE_PERMITIDO_04H1, CAMBIAR_COSTES_POST_RESULTADO_PERMITIDO_04H1,
    COSTE_PRIMARIO_BPS_ANUAL_04H1, COSTE_STRESS_BPS_ANUAL_04H1,
    CREDENCIALES_TRADING_PERMITIDAS_04H1, DESARROLLO_2026_ABIERTO_04H1,
    DIRECCION_04H1, GPT_PERMITIDO_04H1, HAC_LAG_DIAS_04H1,
    HORAS_ESPERADAS_04H1, HYPERLIQUID_PRICE_SOURCE_04H1,
    INVERTIR_DIRECCION_POST_RESULTADO_PERMITIDO_04H1, LEVERAGE_POR_PATA_04H1,
    LIVE_PERMITIDO_04H1, MAX_DRAWDOWN_ECONOMICO_04H1,
    MAX_DRAWDOWN_PRODUCCION_04H1, MIN_ACTIVOS_POSITIVOS_POR_ANIO_04H1,
    OPTIMIZAR_LEVERAGE_POST_RESULTADO_PERMITIDO_04H1,
    OXARCHIVE_MARK_HISTORICO_OBLIGATORIO_04H1, OXARCHIVE_ORACLE_HISTORICO_OBLIGATORIO_04H1,
    OXARCHIVE_PRICE_INTERVAL_04H1, PAPER_OPERATIVO_PERMITIDO_04H1,
    PEOR_ANIO_CAPITAL_MIN_04H1, PROBE_COBERTURA_MIN_04H1, PROBE_HORAS_ESPERADAS_04H1,
    RENDER_PERMITIDO_04H1, REQUIERE_GATE_PRECIOS_ANTES_DE_PNL_04H1,
    RETORNO_MEDIO_ANUAL_CAPITAL_MIN_04H1, SELECCION_POST_RESULTADO_PERMITIDA_04H1,
    SHARPE_ECONOMICO_MIN_04H1, SHARPE_PRODUCCION_MIN_04H1, TSTAT_HAC_ABS_MIN_04H1,
    USAR_CANDLES_COMO_MARK_PERMITIDO_04H1, USAR_CANDLES_COMO_ORACLE_PERMITIDO_04H1,
    VENUE_LONG_04H1, VENUE_SHORT_04H1,
)


def test_04h1_universo_direccion_y_periodo_estan_congelados():
    assert ACTIVOS_04H1 == ("BTC", "ETH", "SOL")
    assert ANIOS_04H1 == (2024, 2025)
    assert VENUE_LONG_04H1 == "BINANCE_USDM_PERPETUAL"
    assert VENUE_SHORT_04H1 == "HYPERLIQUID_PERPETUAL"
    assert DIRECCION_04H1 == "LONG_BINANCE_SHORT_HYPERLIQUID"
    assert DESARROLLO_2026_ABIERTO_04H1 is False


def test_04h1_costes_leverage_y_gates_no_se_relajan():
    assert LEVERAGE_POR_PATA_04H1 == Decimal("2")
    assert COSTE_PRIMARIO_BPS_ANUAL_04H1 == Decimal("60")
    assert COSTE_STRESS_BPS_ANUAL_04H1 == Decimal("120")
    assert SHARPE_ECONOMICO_MIN_04H1 == Decimal("1.0")
    assert MAX_DRAWDOWN_ECONOMICO_04H1 == Decimal("0.10")
    assert TSTAT_HAC_ABS_MIN_04H1 == Decimal("1.96")
    assert RETORNO_MEDIO_ANUAL_CAPITAL_MIN_04H1 == Decimal("0.05")
    assert PEOR_ANIO_CAPITAL_MIN_04H1 == Decimal("0.02")
    assert SHARPE_PRODUCCION_MIN_04H1 == Decimal("2.0")
    assert MAX_DRAWDOWN_PRODUCCION_04H1 == Decimal("0.075")
    assert HAC_LAG_DIAS_04H1 == 7
    assert MIN_ACTIVOS_POSITIVOS_POR_ANIO_04H1 == 2


def test_04h1_congela_fuentes_y_gate_completo():
    assert HYPERLIQUID_PRICE_SOURCE_04H1 == "0XARCHIVE_PRICE_HISTORY"
    assert OXARCHIVE_PRICE_INTERVAL_04H1 == "1h"
    assert OXARCHIVE_ORACLE_HISTORICO_OBLIGATORIO_04H1 is True
    assert OXARCHIVE_MARK_HISTORICO_OBLIGATORIO_04H1 is True
    assert API_KEY_DATOS_0XARCHIVE_PERMITIDA_04H1 is True
    assert USAR_CANDLES_COMO_ORACLE_PERMITIDO_04H1 is False
    assert USAR_CANDLES_COMO_MARK_PERMITIDO_04H1 is False
    assert PROBE_HORAS_ESPERADAS_04H1 == 168
    assert PROBE_COBERTURA_MIN_04H1 == Decimal("0.99")
    assert HORAS_ESPERADAS_04H1 == 17544
    assert BARRAS_8H_ESPERADAS_04H1 == 2193
    assert REQUIERE_GATE_PRECIOS_ANTES_DE_PNL_04H1 is True
    assert CALCULAR_PNL_SI_GATE_COMPLETO_PASA_04H1 is True
    assert CALCULAR_PNL_SIN_GATE_PERMITIDO_04H1 is False


def test_04h1_prohibe_rescate_post_hoc_y_produccion():
    assert SELECCION_POST_RESULTADO_PERMITIDA_04H1 is False
    assert INVERTIR_DIRECCION_POST_RESULTADO_PERMITIDO_04H1 is False
    assert CAMBIAR_COSTES_POST_RESULTADO_PERMITIDO_04H1 is False
    assert OPTIMIZAR_LEVERAGE_POST_RESULTADO_PERMITIDO_04H1 is False
    assert GPT_PERMITIDO_04H1 is False
    assert CREDENCIALES_TRADING_PERMITIDAS_04H1 is False
    assert PAPER_OPERATIVO_PERMITIDO_04H1 is False
    assert LIVE_PERMITIDO_04H1 is False
    assert RENDER_PERMITIDO_04H1 is False
