"""BOT 2.0-04D-2: protocolo de metadata privada read-only para carry 04C-2.

No envía órdenes, no cambia configuración de cuenta y no autoriza producción.
"""

SIMBOLOS_04D2 = ("BTCUSDT", "ETHUSDT")

SPOT_BASE_URL_04D2 = "https://api.binance.com"
FUTURES_BASE_URL_04D2 = "https://fapi.binance.com"

SPOT_COMMISSION_PATH_04D2 = "/api/v3/account/commission"
FUTURES_COMMISSION_PATH_04D2 = "/fapi/v1/commissionRate"
LEVERAGE_BRACKET_PATH_04D2 = "/fapi/v1/leverageBracket"
MULTI_ASSETS_MODE_PATH_04D2 = "/fapi/v1/multiAssetsMargin"
FUTURES_ACCOUNT_CONFIG_PATH_04D2 = "/fapi/v1/accountConfig"

API_KEY_ENV_04D2 = "BINANCE_API_KEY"
API_SECRET_ENV_04D2 = "BINANCE_API_SECRET"
READONLY_OPT_IN_ENV_04D2 = "ALLOW_04D2_ACCOUNT_READONLY"

RECV_WINDOW_MS_04D2 = 5000
TIMEOUT_SEGUNDOS_04D2 = 20

# Seguridad absoluta de esta etapa.
HTTP_METHODS_PERMITIDOS_04D2 = ("GET",)
ORDENES_PERMITIDAS_04D2 = False
CAMBIOS_CUENTA_PERMITIDOS_04D2 = False
PAPER_OPERATIVO_PERMITIDO_04D2 = False
LIVE_PERMITIDO_04D2 = False
RENDER_PERMITIDO_04D2 = False
DESARROLLO_2026_RETORNOS_ABIERTO_04D2 = False
RECALIBRAR_04C2_PERMITIDO_04D2 = False

STATUS_READY_04D2 = "AUDITOR_METADATA_READY_04D2"
STATUS_NO_CREDS_04D2 = "METADATA_CUENTA_NO_DISPONIBLE_04D2"
STATUS_APTA_04D2 = "METADATA_CUENTA_APTA_04D2"
STATUS_ERROR_04D2 = "METADATA_CUENTA_ERROR_04D2"
