from __future__ import annotations

from decimal import Decimal

# BOT 2.0 — 04H-1
# Protocolo económico congelado ANTES de observar PnL cross-venue 2024-2025.

ACTIVOS_04H1 = ("BTC", "ETH", "SOL")
ANIOS_04H1 = (2024, 2025)

VENUE_LONG_04H1 = "BINANCE_USDM_PERPETUAL"
VENUE_SHORT_04H1 = "HYPERLIQUID_PERPETUAL"
DIRECCION_04H1 = "LONG_BINANCE_SHORT_HYPERLIQUID"

PESO_POR_ACTIVO_04H1 = Decimal("0.3333333333333333333333333333")
LEVERAGE_POR_PATA_04H1 = Decimal("2")

COSTE_PRIMARIO_BPS_ANUAL_04H1 = Decimal("60")
COSTE_STRESS_BPS_ANUAL_04H1 = Decimal("120")

# Fuente histórica Hyperliquid congelada antes del PnL.
# La vía 0xArchive quedó descartada para el gate oficial porque priceHistory no
# alcanzó 99% de cobertura y el fallback exacto de open_interest no aportó los
# timestamps faltantes. No se permite interpolar ni usar candles como proxy.
#
# La fuente oficial pasa a ser el archivo requester-pays de Hyperliquid:
# s3://hyperliquid-archive/asset_ctxs/{YYYYMMDD}.csv.lz4
# El usuario autorizó explícitamente una prueba acotada de un solo día antes de
# descargar 2024-2025. El probe debe usar credenciales AWS de lectura fuera del
# repositorio y RequestPayer=requester.
HYPERLIQUID_PRICE_SOURCE_04H1 = "HYPERLIQUID_OFFICIAL_ASSET_CTXS_REQUESTER_PAYS"
HYPERLIQUID_ASSET_CTXS_BUCKET_04H1 = "hyperliquid-archive"
HYPERLIQUID_ASSET_CTXS_PREFIX_04H1 = "asset_ctxs"
HYPERLIQUID_REQUESTER_PAYS_04H1 = True
HYPERLIQUID_PROBE_DATE_04H1 = "20240101"
HYPERLIQUID_PROBE_DIAS_MAX_04H1 = 1
HYPERLIQUID_ORACLE_HISTORICO_OBLIGATORIO_04H1 = True
HYPERLIQUID_MARK_HISTORICO_OBLIGATORIO_04H1 = True
AWS_CREDENCIALES_EN_REPO_PERMITIDAS_04H1 = False
AWS_REQUESTER_PAYS_AUTORIZADO_04H1 = True

# Constantes de la vía descartada se conservan únicamente para trazabilidad de
# auditoría y para que los scripts históricos de calidad sigan siendo legibles.
OXARCHIVE_BASE_URL_04H1 = "https://api.0xarchive.io"
OXARCHIVE_PRICE_INTERVAL_04H1 = "1h"
OXARCHIVE_OI_INTERVAL_04H1 = "1h"
OXARCHIVE_MARK_HISTORICO_OBLIGATORIO_04H1 = True
OXARCHIVE_ORACLE_HISTORICO_OBLIGATORIO_04H1 = True
OXARCHIVE_OI_FALLBACK_EXACTO_PERMITIDO_04H1 = False
OXARCHIVE_OI_NEAREST_PERMITIDO_04H1 = False
API_KEY_DATOS_0XARCHIVE_PERMITIDA_04H1 = False
USAR_CANDLES_COMO_ORACLE_PERMITIDO_04H1 = False
USAR_CANDLES_COMO_MARK_PERMITIDO_04H1 = False

PROBE_DESDE_04H1 = "2024-01-01T00:00:00Z"
PROBE_HASTA_04H1 = "2024-01-02T00:00:00Z"
PROBE_HORAS_ESPERADAS_04H1 = 24
PROBE_COBERTURA_MIN_04H1 = Decimal("0.99")

DESDE_04H1 = "2024-01-01T00:00:00Z"
HASTA_EXCLUSIVO_04H1 = "2026-01-01T00:00:00Z"
HORAS_ESPERADAS_04H1 = 17544
BARRAS_8H_ESPERADAS_04H1 = 2193
COBERTURA_PRECIOS_MIN_04H1 = Decimal("0.99")
COBERTURA_FUNDING_HL_MIN_04H1 = Decimal("0.99")
COBERTURA_ALINEADA_8H_MIN_04H1 = Decimal("0.99")
BINANCE_DATA_URL_04H1 = "https://data.binance.vision/data"
BINANCE_SYMBOLS_04H1 = {"BTC": "BTCUSDT", "ETH": "ETHUSDT", "SOL": "SOLUSDT"}
BINANCE_INTERVALO_PRECIO_04H1 = "8h"

BASE_UNITS_04H1 = Decimal("1")
HAC_LAG_DIAS_04H1 = 7
MIN_ACTIVOS_POSITIVOS_POR_ANIO_04H1 = 2

SHARPE_ECONOMICO_MIN_04H1 = Decimal("1.0")
MAX_DRAWDOWN_ECONOMICO_04H1 = Decimal("0.10")
TSTAT_HAC_ABS_MIN_04H1 = Decimal("1.96")

RETORNO_MEDIO_ANUAL_CAPITAL_MIN_04H1 = Decimal("0.05")
PEOR_ANIO_CAPITAL_MIN_04H1 = Decimal("0.02")
SHARPE_PRODUCCION_MIN_04H1 = Decimal("2.0")
MAX_DRAWDOWN_PRODUCCION_04H1 = Decimal("0.075")

SELECCION_POST_RESULTADO_PERMITIDA_04H1 = False
INVERTIR_DIRECCION_POST_RESULTADO_PERMITIDO_04H1 = False
CAMBIAR_COSTES_POST_RESULTADO_PERMITIDO_04H1 = False
OPTIMIZAR_LEVERAGE_POST_RESULTADO_PERMITIDO_04H1 = False
GPT_PERMITIDO_04H1 = False
CREDENCIALES_TRADING_PERMITIDAS_04H1 = False
PAPER_OPERATIVO_PERMITIDO_04H1 = False
LIVE_PERMITIDO_04H1 = False
RENDER_PERMITIDO_04H1 = False
DESARROLLO_2026_ABIERTO_04H1 = False

REQUIERE_GATE_PRECIOS_ANTES_DE_PNL_04H1 = True
CALCULAR_PNL_SI_GATE_COMPLETO_PASA_04H1 = True
CALCULAR_PNL_SIN_GATE_PERMITIDO_04H1 = False
