"""Protocolo PREDECLARADO BOT 2.0-04B-v17: perpetual basis -> Spot.

Señal única:
    basis_perp(t) = (SpotClose(t) - FuturesClose(t)) / FuturesClose(t)

Dirección predeclarada: basis más alto -> candidato long Spot. Se elige top-5
y se entra al open Spot de t+1, saliendo al close Spot de t+1. Hurdle 25 bps.
No se prueba el sentido contrario en v17. 2026 permanece cerrado.

Este es basis del PERPETUAL, no el current-quarter basis de la literatura.
"""
from __future__ import annotations

from backend.economia.protocolo_premium_v15 import (
    ANIOS_V15, FOLDS_EXCESO_POSITIVOS_MIN_V15,
    FOLDS_PORTFOLIO_POSITIVOS_MIN_V15, FOLDS_SPREAD_POSITIVOS_MIN_V15,
    HURDLE_ECONOMICO_BPS_V15, MESES_EXCESO_POSITIVOS_MIN_V15,
    MESES_PORTFOLIO_POSITIVOS_MIN_V15, MESES_SPREAD_POSITIVOS_MIN_V15,
    MIN_ANIOS_APTOS_V15, MIN_DIAS_POR_ANIO_V15, MIN_SIMBOLOS_POR_DIA_V15,
    TOP_K_V15,
)
from backend.economia.protocolo_perp_v16 import UNIVERSO_PERP_V16

UNIVERSO_V17 = UNIVERSO_PERP_V16
ANIOS_V17 = ANIOS_V15
TOP_K_V17 = TOP_K_V15
MIN_SIMBOLOS_POR_DIA_V17 = MIN_SIMBOLOS_POR_DIA_V15
HURDLE_ECONOMICO_BPS_V17 = HURDLE_ECONOMICO_BPS_V15
MIN_DIAS_POR_ANIO_V17 = MIN_DIAS_POR_ANIO_V15
MIN_ANIOS_APTOS_V17 = MIN_ANIOS_APTOS_V15
MESES_PORTFOLIO_POSITIVOS_MIN_V17 = MESES_PORTFOLIO_POSITIVOS_MIN_V15
FOLDS_PORTFOLIO_POSITIVOS_MIN_V17 = FOLDS_PORTFOLIO_POSITIVOS_MIN_V15
MESES_EXCESO_POSITIVOS_MIN_V17 = MESES_EXCESO_POSITIVOS_MIN_V15
FOLDS_EXCESO_POSITIVOS_MIN_V17 = FOLDS_EXCESO_POSITIVOS_MIN_V15
MESES_SPREAD_POSITIVOS_MIN_V17 = MESES_SPREAD_POSITIVOS_MIN_V15
FOLDS_SPREAD_POSITIVOS_MIN_V17 = FOLDS_SPREAD_POSITIVOS_MIN_V15

CLASE_BASIS_PROMETEDOR_V17 = "BASIS_PROMETEDOR_V17"
CLASE_BASIS_SIN_SENAL_V17 = "BASIS_SIN_SENAL_V17"
DESARROLLO_2026_ABIERTO_V17 = False
TEST_MAY_JUL_ABIERTO_V17 = False
